### ISSUE TITLE
Ruby Paketo Buildpacks should support Thin apps

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/ruby#2]
**Background**
Thin is a pretty popular Ruby web server, and it would be great if Paketo Buildpacks could support building apps that use Thin. I'm throwing this feature request into the MRI CNB repo as we don't have a language family Ruby repo just yet. 

Notes:
- See https://github.com/paketo-community/mri/issues/18 for a proposal for how we can support generic web server start commands

**Comment by ryanmoran** [comment]
Supported as of https://github.com/paketo-community/ruby/releases/tag/v0.0.10

**Comment by kvedurmu** [comment]
This looks great! I was able to use the latest buildpackage artifact and build this Rails [app](https://github.com/kvedurmu/paketo-samples/tree/master/ruby/thin/hello_rails) that uses Thin. I verified that the start command defaults to port 3000 and also allows me to set a custom `PORT`.

It looks like there's one bug with this implementation which is that detection always relies on presence of a `config.ru` file. Fixing this [issue](https://github.com/paketo-community/thin/issues/4) will resolve this.

I'm closing this out, as I think this first pass is good, but there are a couple followup features here that we should look into:
- https://github.com/paketo-community/ruby/issues/4
- https://github.com/paketo-community/thin/issues/6
- https://github.com/paketo-community/thin/issues/5
