### ISSUE TITLE
Self-nomination as Ruby contributor

### ISSUE THREAD

**Issue by floragj** [paketo-community/ruby#409]
In keeping with [the Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am self-nominating as a contributor to the Ruby language family.

I have recently contributed PRs that [proposed the `rake` buildpack](https://github.com/paketo-community/rake/pull/1/commits) and [implemented it](https://github.com/paketo-community/rake/pull/3), which have been merged.

**Comment by ryanmoran** [comment]
With an affirmative vote from myself and @sophiewigmore, we have a supermajority. We have added you to the Ruby Contributors. Congrats!
