### ISSUE TITLE
Language Family Ruby Paketo Buildpack

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/ruby#5]
We should have a language family Ruby Paketo Buildpack that includes all Ruby Implementation CNBs.

This meta buildpack should have the ID "paketo-community/ruby"

**Comment by ryanmoran** [comment]
@kvedurmu I think this is done, right?

**Comment by kvedurmu** [comment]
@ForestEckhardt mentioned that we were just waiting for some of the Github config propogation work to land so that we could create a Ruby buildpackage artifact. So perhaps we'd have it as soon as the latest set of PRs are merged in?

**Comment by ryanmoran** [comment]
@kvedurmu we have a release with a buildpackage artifact now: https://github.com/paketo-community/ruby/releases/tag/v0.0.1

**Comment by kvedurmu** [comment]
Awesome! This looks great. I've gone ahead and validated that the current buildpackage works to build ruby apps that use the puma web server, so I'm going to go ahead and close this. I'm assuming that as we continue to support other ruby web servers, we'll be making corresponding language family buildpack changes, but we can tackle that in a separate issue.
