### ISSUE TITLE
move to package.toml with images

### ISSUE THREAD

**Issue by drnic** [paketo-community/ruby#58]
The new/proper/standard way for meta buildpacks is to have a `package.toml` pre-baked in this repo looking like:

```toml
dependencies = [
  { image = "gcr.io/paketo-community/mri:0.0.121" },
  { image = "gcr.io/paketo-community/bundler:0.0.107" },
  { image = "gcr.io/paketo-community/bundle-install:0.0.11" },
  { image = "gcr.io/paketo-community/puma:0.0.3" },
]

[buildpack]
  uri = "."
```

To do this we need images uploaded to GCR for each buildpack. Currently they are missing https://console.cloud.google.com/gcr/images/paketo-community/GLOBAL/mri?gcrImageListsize=30

Relates to https://github.com/paketo-community/mri/issues/54

This change will then make it easier to integrate other buildpacks like `procfile` as discussed in https://github.com/paketo-buildpacks/procfile/issues/3#issuecomment-638929970

**Comment by kvedurmu** [comment]
Closing this out. We now have individual buildpackages on GCR (for all language families) and ephemeral package.toml files available (e.g https://github.com/paketo-community/ruby/blob/master/package.toml).
