### ISSUE TITLE
Ruby buildpack for paketo looks like doesn't work

### ISSUE THREAD

**Issue by xiujuan95** [paketo-community/ruby#59]
I use this builder image `gcr.io/paketo-buildpacks/builder:latest` to build my [ruby source code](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/dora). But at detect step, it can't get the related buildpack:
```
{"level":"info","ts":1591328779.063402,"caller":"git/git.go:133","msg":"Successfully initialized and updated submodules in path /workspace/source"}
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
2020/06/05 03:46:20 Skipping step because a previous step failed
2020/06/05 03:46:21 Skipping step because a previous step failed
2020/06/05 03:46:21 Skipping step because a previous step failed
2020/06/05 03:46:22 Skipping step because a previous step failed
```
BTW, before yesterday, it works fine. From yesterday, it alway failed because above error. 

So may I get some opinions from you guys, pls? Thanks a lot!

**Comment by ryanmoran** [comment]
Hi @xiujuan95! The Ruby buildpack is in very active development. It does not support all Ruby apps yet. It looks to me like you are running an app that would be enabled once we integrate the `rackup` buildpack. There is an existing issue that is tracking that feature: https://github.com/paketo-community/ruby/issues/1.

**Comment by drnic** [comment]
This might be resolved by #55

**Comment by xiujuan95** [comment]
@ryanmoran Thanks for your message! I want to know whether there is a stable paketo builder image can be used or not?

**Comment by ryanmoran** [comment]
@xiujuan95 we've completed integrating rackup support into the buildpack. I've tried building the dora app and can see it detecting successfully now. I'm going to go ahead and close this issue. Feel free to reopen this with any other problems you find. Thanks!
