### ISSUE TITLE
v0.0.10 - manifest.json had unexpected number of entries: 2

### ISSUE THREAD

**Issue by drnic** [paketo-community/ruby#79]
```
$ pack build drnic/depot --buildpack gcr.io/paketo-community/ruby:0.0.10
...
ERROR: opening buildpack blob: extracting buildpack paketo-community/ruby@0.0.10 layer (diffID sha256:f3c3cee5dd2ce700b3d1fbf4d517533a87c652d7c83f33c37cdc68aefcae9032): manifest.json had unexpected number of entries: 2
```

I was testing the buildpack against a rails/puma app. I do not get this error with v0.0.9.

**Comment by kvedurmu** [comment]
@drnic I'm closing this out for now, as I believe that this was an intermittent error when we initially started publishing buildpackage artifacts to GCR. If you're still seeing this error feel free to open back up and we can investigate!
